# Generated by Django 2.0.1 on 2018-03-25 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre')),
                ('image', models.ImageField(help_text='SVP, une image respectant les dimensions 263x177.', upload_to='teeuApp/Evenement', verbose_name="Image de l'Evenement")),
                ('date_even', models.DateTimeField(verbose_name="Jour de l'Evenement")),
                ('lieu', models.CharField(max_length=50, verbose_name="Lieu de l'Evenement")),
                ('heure_debut', models.TimeField(verbose_name='De (Heure)')),
                ('heure_fin', models.TimeField(verbose_name='A (Heure)')),
                ('resume', models.TextField(verbose_name="Resume de l'Evenement")),
                ('Information_supplementaire', models.TextField(verbose_name='Information supplementaire')),
                ('date_enreg', models.DateTimeField(auto_now_add=True, verbose_name='Date de Publication')),
                ('date_modif', models.DateTimeField(auto_now=True, verbose_name='Date de derniere Modification')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('theme', models.ImageField(upload_to='teeuApp/theme')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Enseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre')),
                ('predicateur', models.CharField(max_length=50, verbose_name='Predicateur')),
                ('date_pred', models.DateTimeField(verbose_name='Date de la predication')),
                ('date_enreg', models.DateTimeField(auto_now_add=True, verbose_name='Date de Publication')),
                ('date_modif', models.DateTimeField(auto_now=True, verbose_name='Date de derniere Modification')),
                ('predication', models.FileField(max_length=200, upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('photo_profil', models.ImageField(null=True, upload_to='', verbose_name='Photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersetDuJour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verset', models.CharField(max_length=50, verbose_name='Verset')),
                ('textDuVerset', models.TextField(max_length=500, verbose_name='Text du verset')),
                ('jourDePub', models.DateField(null=True, verbose_name='Verset du jour')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
            ],
        ),
    ]
