# Generated by Django 2.0.1 on 2018-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0002_auto_20180325_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignement',
            name='image_dispaly',
            field=models.ImageField(default=True, help_text='SVP, une image respectant les dimensions 263x177.', upload_to='teeuApp/Enseignement/cover', verbose_name='Image de couverture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='predication',
            field=models.FileField(default='img.jpg', max_length=200, null=True, upload_to='teeuApp/Enseignement/fichier'),
        ),
    ]
