# Generated by Django 2.0.1 on 2018-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0003_auto_20180325_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='predication',
            field=models.FileField(max_length=200, upload_to='teeuApp/Enseignement/fichier'),
        ),
    ]
