# Generated by Django 2.0.1 on 2018-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0004_auto_20180329_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignement',
            name='Titre_predicateur',
            field=models.CharField(choices=[('Pasteur', 'Pasteur'), ('Ancien', 'Ancien'), ('Frère', 'Frère'), ('Frère', 'Frère'), ('Madame', 'Madame'), ('Rev.', 'Rev.'), ('Apotre', 'Apotre'), ('Autre', 'Predicateur')], default='Predicateur', max_length=15, verbose_name='Titre du predicateur'),
            preserve_default=False,
        ),
    ]
