# Generated by Django 2.0.1 on 2018-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0005_enseignement_titre_predicateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='Titre_predicateur',
            field=models.CharField(choices=[('Pasteur', 'Pasteur'), ('Ancien', 'Ancien'), ('Frère', 'Frère'), ('Madame', 'Madame'), ('Rev.', 'Rev.'), ('Apotre', 'Apotre'), ('Autre', 'Predicateur')], max_length=15, verbose_name='Titre du predicateur'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='genre',
            field=models.CharField(choices=[('video', 'Video'), ('Audio', 'Audio')], max_length=10, verbose_name='Genre'),
        ),
    ]
