# Generated by Django 2.0.1 on 2018-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0006_auto_20180402_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnailImage', models.ImageField(help_text='SVP, une image respectant les dimensions 500x335.', upload_to='teeuApp/Galerie/thumbnail', verbose_name="Image d'affichage")),
                ('Image', models.ImageField(upload_to='teeuApp/Galerie/Image', verbose_name='Image en taille reel')),
                ('Commentaire', models.TextField(verbose_name='Info')),
                ('date_enreg', models.DateTimeField(auto_now_add=True, verbose_name='Date de Publication')),
                ('date_modif', models.DateTimeField(auto_now=True, verbose_name='Date de derniere Modification')),
            ],
        ),
    ]
