# Generated by Django 2.0.1 on 2018-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0007_galerie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='Commentaire',
            field=models.TextField(null=True, verbose_name='Info'),
        ),
    ]
