# Generated by Django 2.0.1 on 2018-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0008_auto_20180413_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerie',
            name='thumbnailImage',
        ),
        migrations.AlterField(
            model_name='galerie',
            name='Image',
            field=models.ImageField(upload_to='teeuApp/Galerie/Image', verbose_name='Image en taille'),
        ),
    ]
