# Generated by Django 2.0.1 on 2018-04-14 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0009_auto_20180414_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure_fin',
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de fin de l'evenement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_even',
            field=models.DateTimeField(verbose_name="Jour de l'evenement"),
        ),
    ]
