# Generated by Django 2.0.1 on 2018-04-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0010_auto_20180414_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pain_Quotidien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre')),
                ('Text_de_base', models.CharField(max_length=100, verbose_name='Text de base')),
                ('titre_posteur', models.CharField(choices=[('Pasteur', 'Pasteur'), ('Ancien', 'Ancien'), ('Frère', 'Frère'), ('Madame', 'Madame'), ('Rev.', 'Rev.'), ('Apotre', 'Apotre'), ('Autre', 'Predicateur')], max_length=15, verbose_name='Titre du posteur')),
                ('date_enreg', models.DateTimeField(auto_now_add=True, verbose_name='Date de Publication')),
                ('date_modif', models.DateTimeField(auto_now=True, verbose_name='Date de derniere Modification')),
                ('image_dispaly', models.ImageField(help_text='SVP, une image respectant les dimensions 263x177.', upload_to='teeuApp/Pain', verbose_name='Image de couverture')),
                ('Text', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
