# Generated by Django 2.0.1 on 2018-05-12 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teeuApp', '0013_commentaire_pain_reply_pain'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire_pain',
            name='date_commentaire',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
